name: Cache refresh

# Controls when the workflow will run
on:
  schedule:
    - cron:  '0 * * * *'

  workflow_dispatch:

jobs:
  Cache_refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Ping cache refresh endpoint
        run: curl --insecure --max-time 600 --location --request GET 'https://openwastemap.uk/api/refreshcache'
